# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: False

python:
  install:
    - method: pip
      path: ./src/python
      extra_requirements:
        - doc
        - torch

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
